[package]
name = "xid"
version = "0.1.5"
authors = []
edition = "2021"

[lib]
name = "xid"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.27.0"
xid = { git = "https://github.com/thanhxeon2470/xid-rs", branch = "main"}